### ISSUE TITLE
Editor - kana to kanji transition changes the word

### ISSUE THREAD

**Issue by danglotor** [himselfv/wakan#296] opened 2021-04-05 20:59 UTC
In the editor when writing japanese text, upon hitting space bar to pick the desired kanji+translation, the form of some of the words changes.
E.g. I want to write 来た [kita] (came), but the word and reading change to base form 来る [kuru] (come).  (來る same behavior)

**Comment by himselfv** [comment] 2021-05-18 09:29
Confirmed.

Notes to myself:
The problem is in the insert resolution in TfEditor.ResolveInsert(). The algorithm correctly locates 来る/くる, correctly stripes the common tail to 来/く. But then it compares the remaining kana to what was typed, but it's "'きた" and doesn't start with "く". So it doesn't know how many of the typed characters to preserve as a tail, and replaces it entirely.
I'll think what to do here.

**Comment by himselfv** [comment] 2021-05-18 10:03
Fixed by writing a special case for kuru-type verbs (which are thankfully marked by the deflexion routine). Will be included in the next release.

**Closed by himselfv** 2021-05-18 10:03 UTC
